name: DellEMC SMI Virtual Network Microservice
description: |
  (Experimental) DellEMC SMI Virtual Network Microservice 
version: 1.0.0
category: Applications
maintainer: "Katalist Mustang <Prashanth_L_Gowda@dell.com>"
license: # Apache 2.0
projectURL: https://github.com/RackHD/smi-service-virtualnetwork