name: DellEMC SMI Server Configuration Profile Microservice
description: |
  (Experimental) DellEMC SMI Server Configuration Profile Microservice 
version: 1.0.0
category: Applications
maintainer: "Katalist Mustang <Prashanth_L_Gowda@dell.com>"
license: # Apache 2.0
projectURL: https://github.com/RackHD/smi-service-dell-server-configuration-profile