name: DellEMC SMI Server Power-Thermal Monitoring Microservice
description: |
  (Experimental) DellEMC SMI Server Power-Thermal Monitoring Microservice
version: 1.0.0
category: Applications
maintainer: "Katalist Mustang <Prashanth_L_Gowda@dell.com>"
license: # Apache 2.0
projectURL: https://github.com/RackHD/smi-service-dell-server-powerthermal-monitoring