version: '2'
services:
  dell-server-configuration-profile:
    container_name: dell-server-configuration-profile
    image: rackhd/dell-server-configuration-profile:latest
    ports:
    - 46018:46018
    mem_limit: 768m
    environment:
    - "SPRING_PROFILES_ACTIVE=default"
    - _JAVA_OPTIONS=-Xmx128m -Xss256k

