version: '2'
services:
  device-discovery:
    container_name: device-discovery
    image: rackhd/device-discovery:latest
    ports:
    - 46002:46002
    mem_limit: 768m
    environment:
    - "SPRING_PROFILES_ACTIVE=default"
    - _JAVA_OPTIONS=-Xmx128m -Xss228k

  dell-server-action:
    container_name: dell-server-action
    image: rackhd/dell-server-action:latest
    network_mode: "host"
    ports:
    - 46007:46007
    mem_limit: 512m
    environment:
    - "SPRING_PROFILES_ACTIVE=default"
    - _JAVA_OPTIONS=-Xmx64m -Xss256k

  dell-chassis-inventory:
    container_name: dell-chassis-inventory
    image: rackhd/dell-chassis-inventory:latest
    ports:
    - 46001:46001
    mem_limit: 768m
    environment:
    - "SPRING_PROFILES_ACTIVE=default"
    - _JAVA_OPTIONS=-Xmx128m -Xss256k

  dell-server-inventory:
    container_name: dell-server-inventory
    image: rackhd/dell-server-inventory:latest
    ports:
    - 46011:46011
    mem_limit: 1024m
    environment:
    - "SPRING_PROFILES_ACTIVE=default"
    - _JAVA_OPTIONS=-Xmx128m -Xss256k

  dell-server-configuration-profile:
    container_name: dell-server-configuration-profile
    image: rackhd/dell-server-configuration-profile:latest
    ports:
    - 46018:46018
    mem_limit: 768m
    environment:
    - "SPRING_PROFILES_ACTIVE=default"
    - _JAVA_OPTIONS=-Xmx128m -Xss256k

  dell-server-firmwareupdate:
    container_name: dell-server-firmwareupdate
    image: rackhd/dell-server-firmwareupdate:latest
    ports:
    - 46010:46010
    privileged: true
    mem_limit: 1024m
    environment:
    - "SPRING_PROFILES_ACTIVE=default"
    - _JAVA_OPTIONS=-Xmx128m -Xss256k

  virtualnetwork:
    container_name: virtualnetwork
    image: rackhd/virtualnetwork:latest
    depends_on:
    - postgresql
    ports:
    - 46016:46016
    mem_limit: 512m
    environment:
    - "SPRING_PROFILES_ACTIVE=default"
    - _JAVA_OPTIONS=-Xmx64m -Xss256k

  virtualidentity:
    container_name: virtualidentity
    image: rackhd/virtualidentity:latest
    depends_on:
    - postgresql
    ports:
    - 46015:46015
    mem_limit: 512m
    environment:
    - "SPRING_PROFILES_ACTIVE=default"
    - _JAVA_OPTIONS=-Xmx64m -Xss256k

  dell-powerthermal-monitoring:
    container_name: dell-powerthermal-monitoring
    image: rackhd/dell-powerthermal-monitoring:latest
    ports:
    - 46019:46019
    mem_limit: 768m
    environment:
    - "SPRING_PROFILES_ACTIVE=default"
    - _JAVA_OPTIONS=-Xmx128m -Xss256k

  postgresql:
    container_name: postgresql
    image: postgres:9.6.1-alpine
    ports:
    - 5433:5432
    mem_limit: 512m
    environment:
      - POSTGRES_PASSWORD=Dell123$$
